name: Fetch YouTube Data

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch YouTube Data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
         curl "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=UUB52lQ_buqcN4OPceA-c-Iw&key=${YOUTUBE_API_KEY}" -o src/public/data/youtubeData.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/public/data/youtubeData.json
          git commit -m "Update YouTube data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
